/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/app/**/*.{js,ts,jsx,tsx}",
    "./src/lib/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        navy: '#181d26',
        'airtable-blue': '#1b61c9',
        spotlight: 'rgba(249,252,255,0.97)',
        success: '#006400',
        'text-weak': 'rgba(4,14,32,0.69)',
        'secondary-active': 'rgba(7,12,20,0.82)',
        'dark-gray': '#333333',
        'mid-blue': '#254fad',
        border: '#e0e2e6',
        'light-surface': '#f8fafc',
        white: '#ffffff',

        // Semantic tokens from globals.css (with fallbacks)
        brand: 'var(--color-brand, #18E299)',
        'brand-light': 'var(--color-brand-light, #d4fae8)',
        'brand-deep': 'var(--color-brand-deep, #0fa76e)',
        warn: 'var(--color-warn, #c37d0d)',
        info: 'var(--color-info, #3772cf)',
        error: 'var(--color-error, #d45656)',
        text: 'var(--color-text, #0d0d0d)',
        muted: 'var(--gray-400, #888888)',
        'text-error': 'var(--color-error, #d45656)',
        'text-brand': 'var(--color-brand, #18E299)',
        'text-muted': 'var(--gray-400, #888888)',
        'border-brand': 'var(--color-brand, #18E299)',
        'border-border': 'var(--border-subtle, rgba(0,0,0,0.05))',
        'border-error': 'var(--color-error, #d45656)',
        'border-card': 'var(--border-subtle, rgba(0,0,0,0.05))',
        'border-section': 'var(--border-subtle, rgba(0,0,0,0.05))',
        'bg-card': 'var(--color-bg, #ffffff)',
        'bg-featured': 'var(--color-bg, #ffffff)',
        'bg-brand-light': 'var(--color-brand-light, #d4fae8)',
        'bg-brand': 'var(--color-brand, #18E299)',
        'bg-error': 'var(--color-error, #d45656)',
        'bg-info': 'var(--color-info, #3772cf)',
        'bg-warn': 'var(--color-warn, #c37d0d)',
        'bg-muted': 'var(--gray-100, #f5f5f5)',
      },
        safelist: [
          'card',
          'featured-card',
          'button',
          'pill',
          'shadow-card',
          'shadow-featured',
          'rounded-card',
          'rounded-featured',
          'rounded-pill',
          'text-brand',
          'text-error',
          'text-muted',
          'border-brand',
          'border-error',
          'border-card',
          'border-section',
          'bg-card',
          'bg-featured',
          'bg-brand',
          'bg-brand-light',
          'bg-error',
          'bg-info',
          'bg-warn',
          'bg-muted',
        ],
      fontFamily: {
        haas: [
          'Haas',
          '-apple-system',
          'system-ui',
          'Segoe UI',
          'Roboto',
          'sans-serif',
        ],
        'haas-disp': [
          'Haas Groot Disp',
          'Haas',
          '-apple-system',
          'system-ui',
          'Segoe UI',
          'Roboto',
          'sans-serif',
        ],
        display: ['Inter', 'sans-serif'],
        mono: ['Geist Mono', 'monospace'],
      },
      borderRadius: {
        sm: '2px',
        md: '12px',
        card: 'var(--radius-card)',
        section: 'var(--radius-featured)',
        featured: 'var(--radius-featured)',
        pill: 'var(--radius-pill)',
        lg: '32px',
        full: '50%',
      },
      boxShadow: {
        'blue-tint': 'rgba(0,0,0,0.32) 0px 0px 1px, rgba(0,0,0,0.08) 0px 0px 2px, rgba(45,127,249,0.28) 0px 1px 3px, rgba(0,0,0,0.06) 0px 0px 0px 0.5px inset',
        soft: 'rgba(15,48,106,0.05) 0px 0px 20px',
        card: '0 2px 8px 0 rgba(24, 226, 153, 0.04)',
        featured: '0 4px 24px 0 rgba(24, 226, 153, 0.08)',
      },
      letterSpacing: {
        tightest: '-0.02em',
        tighter: '-0.01em',
        tight: '0em',
        normal: '0.01em',
        wide: '0.08em',
        wider: '0.18em',
        widest: '0.28em',
      },
      fontSize: {
        'display-hero': ['48px', { lineHeight: '1.15', fontWeight: '400' }],
        'display-bold': ['48px', { lineHeight: '1.5', fontWeight: '900' }],
        'section-heading': ['40px', { lineHeight: '1.25', fontWeight: '400' }],
        'sub-heading': ['32px', { lineHeight: '1.2', fontWeight: '500' }],
        'card-title': ['24px', { lineHeight: '1.25', fontWeight: '400', letterSpacing: '0.12px' }],
        feature: ['20px', { lineHeight: '1.35', fontWeight: '400', letterSpacing: '0.1px' }],
        body: ['18px', { lineHeight: '1.35', fontWeight: '400', letterSpacing: '0.18px' }],
        'body-medium': ['16px', { lineHeight: '1.3', fontWeight: '500', letterSpacing: '0.12px' }],
        button: ['16px', { lineHeight: '1.25', fontWeight: '500', letterSpacing: '0.08px' }],
        caption: ['14px', { lineHeight: '1.3', fontWeight: '400', letterSpacing: '0.18px' }],
      },
      screens: {
        xs: '425px',
        sm: '640px',
        md: '768px',
        lg: '1024px',
        xl: '1280px',
        '2xl': '1664px',
      },
    },
  },
  plugins: [],
};
